# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Michael Teti
tagline:          'A Jekyll theme'
description:      'Computational neuroscience and machine learning. Understanding how we perceive the world.'
url:              http://michaelteti.github.io
baseurl:          /

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/MichaelTeti/
